import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      "**/node_modules/",
      "**/.next/",
      "**/out/",
      "**/.generated/",
      "**/app/", // generated by CLI at build time
      "template/", // scaffolding template copied into new projects
    ],
  },

  // Base JS recommended rules for all files
  eslint.configs.recommended,

  // TypeScript recommended (type-aware off — keeps lint fast without requiring a build)
  ...tseslint.configs.recommended,

  // Allow underscore-prefixed variables to be unused (common convention)
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Overrides for plain CommonJS scripts (cli.js, bin.js, copy-template.js)
  {
    files: ["**/*.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: globals.node,
    },
    rules: {
      // These CJS files use require() which typescript-eslint flags
      "@typescript-eslint/no-require-imports": "off",
    },
  },
);
